name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    needs: [lint, test]
    environment:
      name: pypi
      url: https://pypi.org/p/jsonstar
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Build package
        run: |
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
